### ISSUE TITLE
NFD master panics when no matchFeatures are defined in NodeFeatureRule

### ISSUE THREAD

**Issue by PiotrProkop** [kubernetes-sigs/node-feature-discovery#1170]
**What happened**:

```sh
I0421 13:44:17.450121       1 nfd-master.go:594] will process all nodes in the cluster
panic: assignment to entry in nil map

goroutine 163 [running]:
sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1.(*Features).InsertAttributeFeatures(...)
        /go/node-feature-discovery/pkg/apis/nfd/v1alpha1/feature.go:62
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).processNodeFeatureRule(0xc00080e8c0, 0xc000040720)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:924 +0x9a9
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).refreshNodeFeatures(0xc00080e8c0, 0x0?, {0xc0007ae180, 0x2f}, 0xc000803360?, 0xc000d65790?, 0x857f38?)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:746 +0xdc
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateOneNode(0xc00080e8c0, {0xc0007ae180, 0x2f})
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:675 +0x487
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateAllNodes(0xc00080e8c0)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:607 +0x170
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateHandler(0xc00080e8c0)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:335 +0x1cc
created by sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).Run
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:225 +0x6fe
```

**What you expected to happen**:

Log error or apply extended resources 😄 

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rdt-l3-closid-extended-rule
spec:
  rules:
    - name: "rdt l3 closid extended rule"
      extendedResources:
        feature.node.kubernetes.io/rdtl3_closid: "@cpu.rdt.RDTL3CA_NUM_CLOSID"
```

I have also tried it with empty list, still panicking:
```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rdt-l3-closid-extended-rule
spec:
  rules:
    - name: "rdt l3 closid extended rule"
      extendedResources:
        feature.node.kubernetes.io/rdtl3_closid: "@cpu.rdt.RDTL3CA_NUM_CLOSID"
      matchFeatures: []
```

**Anything else we need to know?**:

Running from `v0.13.0` tag

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23

**Comment by ArangoGutierrez** [comment]
testing both yaml provided as example, I get the expected log messages but no panic.

**Comment by ArangoGutierrez** [comment]
This issue is a good topic to also discuss at https://github.com/kubernetes-sigs/node-feature-discovery/issues/1131

**Comment by ArangoGutierrez** [comment]
Actually ran the test on 1.23 (minikube) and no panic there either, any extra config for that deployment @PiotrProkop ?

**Comment by ArangoGutierrez** [comment]
```bash
E0421 14:24:33.987365       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:25:33.992051       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:25:33.993209       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:26:33.934520       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:26:33.935558       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:27:33.976874       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:27:33.977439       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:28:33.985259       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:28:33.986019       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:29:33.940608       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:29:33.940951       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:30:33.987850       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:30:33.988325       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:31:33.963913       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:31:33.964782       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
I0421 14:32:33.990239       1 nfd-master.go:574] received labeling request for node "minikube"
E0421 14:32:33.990509       1 nfd-master.go:718] element RDTL3CA_NUM_CLOSID not foundon feature cpu.rdt. Ignoring Extended Resource "feature.node.kubernetes.io/rdtl3_closid"
```

half of the logs are for example `#1` and other half for example `#2` , no panic observed

**Comment by PiotrProkop** [comment]
> Actually ran the test on 1.23 (minikube) and no panic there either, any extra config for that deployment @PiotrProkop ?
> 
> so far tested on 1.27-latest and 1.23.7, observed no panics

for `nfd-master`:
```yaml
      - args:
        - --enable-nodefeature-api
        command:
        - nfd-master
```
for `nfd-worker`:
```yaml
        - --config=/etc/nfd_config/nfd-worker.conf
        - --enable-nodefeature-api
        command:
        - nfd-worker
```

where config is:
```json
{
   "core": {
      "noPublish": false,
      "sleepInterval": "-1s",
      "labelSources": ["custom"]
   },
   "sources": {
      "custom":[
        {
          "name": "RDTL3CA",
          "labels": {
            "feature.node.kubernetes.io/cpu-rdt.RDTL3CA": "true"
          },
          "matchFeatures": [
           {
             "feature": "cpu.rdt",
             "matchExpressions": {
               "RDTL3CA": {"op": "Exists"}
             }
           }
         ]
        }
      ]
   }
}

```

**Comment by ArangoGutierrez** [comment]
still unable to crash, will continue testing

**Comment by marquiz** [comment]
Thanks for the report @PiotrProkop! I was now able to reproduce this. Finding a fix...

**Comment by PiotrProkop** [comment]
> still unable to crash, will continue testing

I know what is the problem :) 
Not all nodes in my cluster have corresponding `NodeFeatures` object. And we have bug in initializing `NodeFeatureSpec` when it's not found:
```go
	features := &nfdv1alpha1.NodeFeatureSpec{}
	annotations := Annotations{}

	if len(objs) > 0 {
		// Merge in features
		//
		// NOTE: changing the rule api to support handle multiple objects instead
		// of merging would probably perform better with lot less data to copy.
		features = objs[0].Spec.DeepCopy()
		for _, o := range objs[1:] {
			o.Spec.MergeInto(features)
		}

		utils.KlogDump(4, "Composite NodeFeatureSpec after merge:", "  ", features)

		if objs[0].Namespace == m.namespace && objs[0].Name == nodeName {
			// This is the one created by nfd-worker
			if v := objs[0].Annotations[nfdv1alpha1.WorkerVersionAnnotation]; v != "" {
				annotations[nfdv1alpha1.WorkerVersionAnnotation] = v
			}
		}
	}
```
if `objs` for node are 0 we will not initialize `Features.Attributes` and Golang will use default value for map which is `nil` .

**Comment by PiotrProkop** [comment]
@marquiz we should just create constructor for `nfdv1alpha1.NodeFeatureSpec{}` something like:
```go
funcnewEmptyFeatureSpec() *nfdv1alpha1.NodeFeatureSpec{
return ...
}

**Comment by marquiz** [comment]
Yeah, this is a bad one. Will submit a fix soon
