### ISSUE TITLE
Document supported k8s versions

### ISSUE THREAD

**Issue by Agalin** [kubernetes-sigs/node-feature-discovery#1257]
**What would you like to be added**:

Document currently compatible versions of k8s in readme or docs and last verison of NFD working on a particular k8s version.

**Why is this needed**:

I'm currently working on deploying NFD in our environment. We have multiple clusters using k8s 1.23 and 1.27. To my surprise, Helm deployment working just fine on 1.27 cluster failed with master pod crashlooping on 1.23 clusters. It seems that recent kubernetes API library version bump is the problem - master works fine on 0.13.1.

Ensuring compatibility with old (I'm aware of 1.23 not being supported any more) k8s versions makes no sense but compatibility matrix would be a welcome addition and would save me a few hours of debugging. 😄

**Comment by marquiz** [comment]
Hi @Agalin. NFD really should practically work on any kubernetes version that is still being used as we're only using stable apis. Bumping the patch version of the k8s deps really shouldn't break anything

Could you share more details about your deployment and the failure?

**Comment by Agalin** [comment]
It seems to be some kind of an incompatibility between the latest version of the Kubernetes API library and K8s 1.23 (1.23.10 to be precise).

Master deployed from 0.13.2 crashloops with the following error in logs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1724548]

goroutine 14 [running]:
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateOneNode(0xc000482a00, {0xc000158f60, 0xc})
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:637 +0x108
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateAllNodes(0xc000482a00)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:627 +0x170
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateHandler(0xc000482a00)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:338 +0x1cc
created by sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).Run
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:228 +0x6f8
```

Same config works just fine on k8s 1.27.

Looking at logs, it breaks somewhere between [line 689](https://github.com/kubernetes-sigs/node-feature-discovery/blob/08b9c3486eadd78bc40dcbf02858f8435c07d3ff/pkg/nfd-master/nfd-master.go#L689-L710) and [line 710](https://github.com/kubernetes-sigs/node-feature-discovery/blob/08b9c3486eadd78bc40dcbf02858f8435c07d3ff/pkg/nfd-master/nfd-master.go#L710). It reaches single node update function but doesn't print NodeFeature retrieval error nor `processing of node initiated by NodeFeature API`.

**Comment by Agalin** [comment]
I'm not sure if it's worth debugging, k8s 1.23 is deprecated and even 1.24 will reach EOL next week.

**Comment by marquiz** [comment]
There is some bug in the codebase that v1.23 reveals. I'd like to understand what

**Comment by marquiz** [comment]
@Agalin the issue you were facing should be now fixed in the just released [v0.13.3](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.13.3)

But back to your original issue about supported K8s versions I created #1277

**Comment by Agalin** [comment]
Thanks! Hopefully I'll be able to test it next week.
