### ISSUE TITLE
Running make test with go version >= 1.15 fails

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes-sigs/node-feature-discovery#387]
**What happened**:
Running `make test` with go version >= 1.15 fails with the error:
```
2020/11/18 14:07:50 Node Feature Discovery Master undefined
2020/11/18 14:07:50 NodeName: ''
2020/11/18 14:07:50 Node Feature Discovery Worker undefined
2020/11/18 14:07:50 NodeName: ''
2020/11/18 14:07:50 gRPC server serving on port: 8192
x
Failures:

  * /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go 
  Line 124:
  Expected: nil
  Actual:   'failed to connect: context deadline exceeded'
  goroutine 73 [running]:
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:143 +0x6f
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/reporting/reports.go:103 +0x71
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:176 +0xe6
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:125 +0x66
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1.1.1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:124 +0x59
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x48
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId(0xc00060f410)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x11d
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001e14e0, 0xc00060f3b0, 0xc0006a73a0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x1c8
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x92
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1.1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:123 +0x39d
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:163 +0x48
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId(0xc00051c6c0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x11d
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001e14e0, 0xc00051c660, 0xc000382560)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:162 +0x1c8
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:77 +0x92
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls.func1()
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:112 +0x7a
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/discovery.go:80 +0x24
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:261 +0x125
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:110 +0xf0
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x462
  github.com/jtolds/gls.EnsureGoroutineId.func1()
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc000382540)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc000382540)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc00051c5a0)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xfd
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0001e14e0, 0xc00051c540, 0xc000382500)
        /home/alukiano/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x153
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/context.go:105 +0x231
        /home/alukiano/go/pkg/mod/github.com/smartystreets/goconvey@v1.6.4/convey/doc.go:75 +0xbe
  sigs.k8s.io/node-feature-discovery/pkg/nfd-worker_test.TestRunTls(0xc000602480)
        /home/alukiano/go/src/sigs.k8s.io/node-feature-discovery/pkg/nfd-worker/nfd-worker_test.go:111 +0x358
  testing.tRunner(0xc000602480, 0x170d048)
        /usr/local/go/src/testing/testing.go:1127 +0xef
  created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1178 +0x386
  


50 total assertions

--- FAIL: TestRunTls (60.00s)
FAIL
FAIL    sigs.k8s.io/node-feature-discovery/pkg/nfd-worker       60.028s
```

**What you expected to happen**:
`make test` should pass without any errors.

**How to reproduce it (as minimally and precisely as possible)**:
- install go version >= 1.15
- run `make test`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marquiz** [comment]
Thanks. Need to update the test certs under `test/data` (I think)
